changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Enhancements
      labels:
        - enhancements
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
